--ASCII VE CHAR FONKSIYONLARI
SELECT ASCII('Ö')

SELECT CHAR(214)

--SUBSTRING
SELECT SUBSTRING('ALÝ CAN ÇETÝNER',1,3)

SELECT * FROM CUSTOMERS WHERE CUSTOMERNAME LIKE 'O%'
SELECT * FROM CUSTOMERS WHERE SUBSTRING(CUSTOMERNAME,LEN(CUSTOMERNAME),1)='O'
Onur EYYÜBOÐLU
SELECT LEN('Onur EYYÜBOÐLU')

--CHARINDEX
SELECT CHARINDEX('L','ALÝ CAN ÇETÝNER',1)

--CONCAT
SELECT CONCAT('ALÝ',' ','CAN',' ','ÇETÝNER')
SELECT CONCAT_WS(' ','ALÝ','CAN','ÇETÝNER')

SELECT CONCAT(CUSTOMERNAME,' ',GENDER,' ',NATION),
 CONCAT_WS(' ',CUSTOMERNAME,GENDER,NATION),
* FROM CUSTOMERS

--FORMAT
SELECT FORMAT(GETDATE(),'d','en-us')

--LEFT,RIGHT,LEN
SELECT LEFT('ALÝ CAN ÇETÝNER',4)
SELECT RIGHT('ALÝ CAN ÇETÝNER',7)
SELECT LEN('ALÝ CAN ÇETÝNER')

SELECT LEFT ('ALÝ CAN ÇETÝNER',CHARINDEX(' ','ALÝ CAN ÇETÝNER'))
SELECT RIGHT ('ALÝ CAN ÇETÝNER',LEN('ALÝ CAN ÇETÝNER')-CHARINDEX(' ','ALÝ CAN ÇETÝNER'))

SELECT LEFT ('ALÝ CAN ÇETÝNER',CHARINDEX(' ','ALÝ CAN ÇETÝNER')),RIGHT ('ALÝ CAN ÇETÝNER',LEN('ALÝ CAN ÇETÝNER')-CHARINDEX(' ','ALÝ CAN ÇETÝNER'))
SELECT LEFT (CUSTOMERNAME,CHARINDEX(' ',CUSTOMERNAME)),RIGHT (CUSTOMERNAME,LEN(CUSTOMERNAME)-CHARINDEX(' ',CUSTOMERNAME))
FROM CUSTOMERS

--TRIM,LTRIM,RTRIM
SELECT TRIM(' ALÝ  CAN  ÇETÝNER  ')
SELECT LTRIM(' ALÝ  CAN  ÇETÝNER  ')
SELECT RTRIM(' ALÝ  CAN  ÇETÝNER  ')


--LOWER,UPPER,REVERSE,REPLICATE
SELECT UPPER('ali')
SELECT LOWER('ALÝ')
SELECT REVERSE('ALÝ')
SELECT REPLICATE(1,10)

--REPLACE 
SELECT 'ALÝ CAN ÇETÝNER'
SELECT REPLACE('ALÝ CAN ÇETÝNER','ALÝ CAN','ALÝCAN')

  
DECLARE @CUMLE AS VARCHAR(MAX)        --OBJE OLUÞTURMA(DEÐER ATAMA)

SET @CUMLE=....
