 SELECT
 U.NAMESURNAME_ AS ADSOYAD,
 U.EMAIL MAILADRESI,
 U.GENDER CINSIYET,
 U.BIRTHDATE DOGUMTARIHI,
 C.COUNTRY AS ULKE, CT.CITIES AS SEHIR,
 T.TOWN AS ILCE, D.DISTRICT AS SEMT,
 A.POSTALCODE AS POSTAKODU,
 A.ADDRESSTEXT AS ACIKADRES
 FROM 
 USERS U, ADDRESS A, CITIES CT, TOWN T ,COUNTRIES C ,DISTRICTS D
 WHERE U.ID=A.USERID AND C.ID=A.COUNTRYID AND CT.ID=A.CITYID AND T.ID=A.TOWNID AND D.ID=A.DISTRICTID
 AND U.ID=4 
 --ORDER BY U.NAMESURNAME_