Select U.USERNAME_,A.ADDRESSTEXT,C.COUNTRY,CT.CITIES,T.TOWN
from
USERS U
JOIN ADDRESS A on U.ID=A.USERID
JOIN COUNTRIES C on C.ID=A.COUNTRYID
JOIN CITIES CT on  CT.ID=A.CITYID
JOIN TOWN T on T.ID=A.TOWNID

