SELECT CITY,DATE_,SUM(TOTALPRICE) AS TOTALPRICE
FROM SALES WHERE CITY='ANKARA'
GROUP BY CITY,DATE_
ORDER BY CITY,DATE_

SELECT DATE_,CITY,SUM(TOTALPRICE) AS TOTALPRICE
FROM SALES

WHERE DATE_='2019-01-01'

GROUP BY DATE_,CITY
ORDER BY DATE_,SUM(TOTALPRICE) DESC

