SELECT MIN(AMOUNT),MAX(AMOUNT),COUNT(FICHENO),SUM(AMOUNT),AVG(AMOUNT) FROM SALES 

SELECT * FROM SALES ORDER BY TOTALPRICE

SELECT MIN(TOTALPRICE),MAX(TOTALPRICE),COUNT(TOTALPRICE),SUM(TOTALPRICE),AVG(TOTALPRICE) FROM SALES 
WHERE CITY='ANKARA'
SELECT MIN(TOTALPRICE),MAX(TOTALPRICE),COUNT(TOTALPRICE),SUM(TOTALPRICE),AVG(TOTALPRICE) FROM SALES 
WHERE CITY='ÝSTANBUL'
SELECT MIN(TOTALPRICE),MAX(TOTALPRICE),COUNT(TOTALPRICE),SUM(TOTALPRICE),AVG(TOTALPRICE) FROM SALES 
WHERE CITY='ADANA'


SELECT MIN(TOTALPRICE) AS MINPRICE ,MAX(TOTALPRICE) AS MAXPRICE ,COUNT(TOTALPRICE) AS ROWCOUNT_ ,SUM(TOTALPRICE) AS TOTALPRICE,AVG(TOTALPRICE) AS AVGPRICE FROM SALES
GROUP BY CITY


SELECT TOP 10  CITY,SUM(TOTALPRICE) FROM SALES
GROUP BY CITY
ORDER BY SUM(TOTALPRICE) DESC