SELECT CATEGORY1,CATEGORY2,CATEGORY3,CATEGORY4,
SUM(TOTALPRICE) AS TOTALPRICE,
COUNT(*) AS ROWCOUNT_,
SUM(AMOUNT) AS TOTALAMOUNT

FROM SALES
GROUP BY CATEGORY1,CATEGORY2,CATEGORY3,CATEGORY4
ORDER BY CATEGORY1,CATEGORY2,CATEGORY3,CATEGORY4


SELECT
CITY,COUNT(DISTINCT CUSTOMERNAME) AS UNIQUECUSTOMER,COUNT(DISTINCT FICHENO) CUSTOMERCOUNT,COUNT(*) ITEMCOUNT
FROM SALES 
GROUP BY CITY
ORDER BY CITY



SELECT CITY,SUM(TOTALPRICE) AS TOTALPRICE,COUNT(DISTINCT CUSTOMERNAME) CUSTOMERCOUNT
FROM SALES
GROUP BY CITY
HAVING SUM(TOTALPRICE)>40000
ORDER BY SUM(TOTALPRICE) DESC